name: Deploy Site
on:
  workflow_dispatch:
  schedule:
    - cron:  '0 */2 * * *'

jobs:
  build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@master
    - uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '5.0.100' # SDK Version to use.
    - run: dotnet run -- deploy
      env:
        GITHUB_TOKEN: ${{ secrets.PERSONAL_GITHUB_TOKEN }}
        NETLIFY_TOKEN: ${{ secrets.NETLIFY_TOKEN }}
        ALGOLIA_TOKEN: ${{ secrets.ALGOLIA_TOKEN }}
